--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/RevivalPMMP/PureEntitiesX
branches:
- master
- kniffo80-dev
- Jumping-Rabbits
- MobEvents
- RideableMobs
- damage-reduction
projects:
  PureEntitiesX:
    path: ""
    icon: icon.png
...
