name: PureEntitiesX
main: revivalpmmp\pureentities\PureEntities
version: "1.1"
api: ["2.1.0, 2.0.0"]

load: STARTUP
author: milk0417, now RevivalPMMP
description: Implement all MCPE entities
website: https://github.com/RevivalPMMP/PureEntitiesX
commands: []
