# Default Config File for PureEntitiesX
spawnmonsters: true
spawnanimals: true
# Disabling auto despawning can have a HUGE effect on server performance, and overrun your server with mobs.
auto-despawn: true 

